const actions = {
    GET_BALANCE_REQUEST: "GET_BALANCE_REQUEST",
    GET_BALANCE_REQUEST_SUCCESS: "GET_BALANCE_REQUEST_SUCCESS",
    GET_BALANCE_REQUEST_FAILED: "GET_BALANCE_REQUEST_FAILED",

    GET_BALANCE_REQUEST_DETAILS: "GET_BALANCE_REQUEST_DETAILS",
    GET_BALANCE_REQUEST_DETAILS_SUCCESS: "GET_BALANCE_REQUEST_DETAILS_SUCCESS",
    GET_BALANCE_REQUEST_DETAILS_FAILED: "GET_BALANCE_REQUEST_DETAILS_FAILED",

    UPDATE_BALANCE_REQUEST_STATUS: "UPDATE_BALANCE_REQUEST_STATUS",
    UPDATE_BALANCE_REQUEST_STATUS_SUCCESS: "UPDATE_BALANCE_REQUEST_STATUS_SUCCESS",
    UPDATE_BALANCE_REQUEST_STATUS_FAILED: "UPDATE_BALANCE_REQUEST_STATUS_FAILED",
    UPDATE_BALANCE_REQUEST_STATUS_RESET: "UPDATE_BALANCE_REQUEST_STATUS_RESET",

    get_all_balance_request: (query) => ({
        type: actions.GET_BALANCE_REQUEST,
        query,
    }),

    get_balance_request_details: (id) => ({
        type: actions.GET_BALANCE_REQUEST_DETAILS,
        id,
    }),

    update_balance_request_status: (id, data) => ({
        type: actions.UPDATE_BALANCE_REQUEST_STATUS,
        id,
        data,
    }),
};

export default actions;
