const actions = {
    GET_DOCUMENT_FILE: "GET_DOCUMENT_FILE",
    GET_DOCUMENT_FILE_SUCCESS: "GET_DOCUMENT_FILE_SUCCESS",
    GET_DOCUMENT_FILE_FAILED: "GET_DOCUMENT_FILE_FAILED",

    CREATE_DOCUMENT_FILE: "CREATE_DOCUMENT_FILE",
    CREATE_DOCUMENT_FILE_SUCCESS: "CREATE_DOCUMENT_FILE_SUCCESS",
    CREATE_DOCUMENT_FILE_FAILED: "CREATE_DOCUMENT_FILE_FAILED",
    CREATE_DOCUMENT_FILE_RESET: "CREATE_DOCUMENT_FILE_RESET",
    OPEN_ADD_CREATE_FILE_MODAL: "OPEN_ADD_CREATE_FILE_MODAL",
    CLOSE_ADD_CREATE_FILE_MODAL: "CLOSE_ADD_CREATE_FILE_MODAL",

    DELETE_DOCUMENT_FILE: "DELETE_DOCUMENT_FILE",
    DELETE_DOCUMENT_FILE_SUCCESS: "DELETE_DOCUMENT_FILE_SUCCESS",
    DELETE_DOCUMENT_FILE_FAILED: "DELETE_DOCUMENT_FILE_FAILED",
    DELETE_DOCUMENT_FILE_RESET: "DELETE_DOCUMENT_FILE_RESET",

    UPDATE_DOCUMENT_FILE: "UPDATE_DOCUMENT_FILE",
    UPDATE_DOCUMENT_FILE_SUCCESS: "UPDATE_DOCUMENT_FILE_SUCCESS",
    UPDATE_DOCUMENT_FILE_FAILED: "UPDATE_DOCUMENT_FILE_FAILED",
    UPDATE_DOCUMENT_FILE_RESET: "UPDATE_DOCUMENT_FILE_RESET",
    OPEN_UPDATE_DOCUMENT_FILE_MODAL: "OPEN_UPDATE_DOCUMENT_FILE_MODAL",
    CLOSE_UPDATE_DOCUMENT_FILE_MODAL: "CLOSE_UPDATE_DOCUMENT_FILE_MODAL",

    GET_DOCUMENT_FILE_CONTENT_BY_TYPE: "GET_DOCUMENT_FILE_CONTENT_BY_TYPE",
    GET_DOCUMENT_FILE_CONTENT_BY_TYPE_SUCCESS: "GET_DOCUMENT_FILE_CONTENT_BY_TYPE_SUCCESS",
    GET_DOCUMENT_FILE_CONTENT_BY_TYPE_FAILED: "GET_DOCUMENT_FILE_CONTENT_BY_TYPE_FAILED",

    CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE: "CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE",
    CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE_SUCCESS: "CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE_SUCCESS",
    CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE_FAILED: "CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE_FAILED",
    CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE_RESET: "CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE_RESET",
    OPEN_ADD_CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE: "OPEN_ADD_CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE",
    CLOSE_ADD_CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE: "CLOSE_ADD_CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE",

    GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE: "GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE",
    GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_SUCCESS: "GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_SUCCESS",
    GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_FAILED: "GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_FAILED",
    OPEN_GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_MODAL: "OPEN_GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_MODAL",
    CLOSE_GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_MODAL: "CLOSE_GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_MODAL",

    DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE: "DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE",
    DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE_SUCCESS: "DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE_SUCCESS",
    DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE_FAILED: "DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE_FAILED",
    DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE_RESET: "DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE_RESET",

    UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE: "UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE",
    UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_SUCCESS: "UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_SUCCESS",
    UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_FAILED: "UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_FAILED",
    UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_RESET: "UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_RESET",
    OPEN_UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_MODAL: "OPEN_UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_MODAL",
    CLOSE_UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_MODAL: "CLOSE_UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_MODAL",

    get_document_file: (query) => ({
        type: actions.GET_DOCUMENT_FILE,
        query,
    }),

    create_document_file: (data) => ({
        type: actions.CREATE_DOCUMENT_FILE,
        data,
    }),

    delete_document_file: (data) => ({
        type: actions.DELETE_DOCUMENT_FILE,
        data,
    }),

    update_document_file: (data) => ({
        type: actions.UPDATE_DOCUMENT_FILE,
        data,
    }),

    create_document_file_content: (data) => ({
        type: actions.CREATE_DOCUMENT_FILE_CONTENT_BY_TYPE,
        data,
    }),

    get_document_file_content_by_id: (id) => ({
        type: actions.GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE,
        id,
    }),

    update_document_file_content: (id, data) => ({
        type: actions.UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE,
        id,
        data,
    }),

    delete_document_file_content: (id) => ({
        type: actions.DELETE_DOCUMENT_FILE_CONTENT_BY_TYPE,
        id,
    }),

    update_document_file_content_by_id: (payload) => ({
        type: actions.OPEN_UPDATE_DOCUMENT_FILE_CONTENT_BY_TYPE_MODAL,
        payload,
    }),

    open_view_document_file_content_modal: (payload) => ({
        type: actions.OPEN_GET_DOCUMENT_FILE_CONTENT_ID_BY_TYPE_MODAL,
        payload,
    }),
};

export default actions;
