const actions = {
    GET_MARKET_MAKER: "GET_MARKET_MAKER",
    GET_MARKET_MAKER_SUCCESS: "GET_MARKET_MAKER_SUCCESS",
    GET_MARKET_MAKER_FAILED: "GET_MARKET_MAKER_FAILED",

    GET_MARKET_MAKER_DETAILS: "GET_MARKET_MAKER_DETAILS",
    GET_MARKET_MAKER_DETAILS_SUCCESS: "GET_MARKET_MAKER_DETAILS_SUCCESS",
    GET_MARKET_MAKER_DETAILS_FAILED: "GET_MARKET_MAKER_DETAILS_FAILED",

    ADD_MARKET_MAKER: "ADD_MARKET_MAKER",
    ADD_MARKET_MAKER_SUCCESS: "ADD_MARKET_MAKER_SUCCESS",
    ADD_MARKET_MAKER_FAILED: "ADD_MARKET_MAKER_FAILED",
    ADD_MARKET_MAKER_RESET: "ADD_MARKET_MAKER_RESET",

    UPDATE_MARKET_MAKER: "UPDATE_MARKET_MAKER",
    UPDATE_MARKET_MAKER_SUCCESS: "UPDATE_MARKET_MAKER_SUCCESS",
    UPDATE_MARKET_MAKER_FAILED: "UPDATE_MARKET_MAKER_FAILED",
    UPDATE_MARKET_MAKER_RESET: "UPDATE_MARKET_MAKER_RESET",

    UPDATE_MARKET_MAKER_STATUS: "UPDATE_MARKET_MAKER_STATUS",
    UPDATE_MARKET_MAKER_STATUS_SUCCESS: "UPDATE_MARKET_MAKER_STATUS_SUCCESS",
    UPDATE_MARKET_MAKER_STATUS_FAILED: "UPDATE_MARKET_MAKER_STATUS_FAILED",
    UPDATE_MARKET_MAKER_STATUS_RESET: "UPDATE_MARKET_MAKER_STATUS_RESET",

    get_all_market_maker: (query) => ({
        type: actions.GET_MARKET_MAKER,
        query,
    }),

    get_market_maker_details: (id) => ({
        type: actions.GET_MARKET_MAKER_DETAILS,
        id,
    }),

    add_market_maker: (data) => ({
        type: actions.ADD_MARKET_MAKER,
        data,
    }),

    update_market_maker: (id, data) => ({
        type: actions.UPDATE_MARKET_MAKER,
        data,
        id,
    }),
    update_market_maker_status: (id, data) => ({
        type: actions.UPDATE_MARKET_MAKER_STATUS,
        id,
    }),
};

export default actions;
