const actions = {
    GET_ALL_PARTNER_BANK: 'GET_ALL_PARTNER_BANK',
    GET_ALL_PARTNER_BANK_SUCCESS: 'GET_ALL_PARTNER_BANK_SUCCESS',
    GET_ALL_PARTNER_BANK_FAILED: 'GET_ALL_PARTNER_BANK_FAILED',

    GET_PARTNER_BANK_BYID: 'GET_PARTNER_BANK_BYID',
    GET_PARTNER_BANK_BYID_SUCCESS: 'GET_PARTNER_BANK_BYID_SUCCESS',
    GET_PARTNER_BANK_BYID_FAILED: 'GET_PARTNER_BANK_BYID_FAILED',

    GET_PARTNER_BANK_AGENT_ID: 'GET_PARTNER_BANK_AGENT_ID',
    GET_PARTNER_BANK_AGENT_ID_SUCCESS: 'GET_PARTNER_BANK_AGENT_ID_SUCCESS',
    GET_PARTNER_BANK_AGENT_ID_FAILED: 'GET_PARTNER_BANK_AGENT_ID_FAILED',
    GET_PARTNER_BANK_AGENT_ID_RESET: 'GET_PARTNER_BANK_AGENT_ID_RESET',

    CREATE_PARTNER_BANK: 'CREATE_PARTNER_BANK',
    CREATE_PARTNER_BANK_SUCCESS: 'CREATE_PARTNER_BANK_SUCCESS',
    CREATE_PARTNER_BANK_FAILED: 'CREATE_PARTNER_BANK_FAILED',

    UPDATE_PARTNER_BANK: 'UPDATE_PARTNER_BANK',
    UPDATE_PARTNER_BANK_SUCCESS: 'UPDATE_PARTNER_BANK_SUCCESS',
    UPDATE_PARTNER_BANK_FAILED: 'UPDATE_PARTNER_BANK_FAILED',
    UPDATE_PARTNER_BANK_RESET: 'UPDATE_PARTNER_BANK_RESET',

    DELETE_PARTNER_BANK: 'DELETE_PARTNER_BANK',
    DELETE_PARTNER_BANK_SUCCESS: 'DELETE_PARTNER_BANK_SUCCESS',
    DELETE_PARTNER_BANK_FAILED: 'DELETE_PARTNER_BANK_FAILED',

    get_all_partner_bank: (query) => ({
        type: actions.GET_ALL_PARTNER_BANK,
        query
    }),

    get_partner_bank_byid: (id) => ({
        type: actions.GET_PARTNER_BANK_BYID,
        id
    }),

    get_partner_bank_agent_id: (id) => ({
        type: actions.GET_PARTNER_BANK_AGENT_ID,
        id,
    }),

    create_partner_bank: (data) => ({
        type: actions.CREATE_PARTNER_BANK,
        data
    }),

    update_partner_bank: (data) => ({
        type: actions.UPDATE_PARTNER_BANK,
        data
    }),

    delete_partner_bank: (id) => ({
        type: actions.DELETE_PARTNER_BANK,
        id
    }),
};

export default actions;