const fundingSourceActions = {
    GET_FUNDING_SOURCES: "GET_FUNDING_SOURCES",
    GET_FUNDING_SOURCES_SUCCESS: "GET_FUNDING_SOURCES_SUCCESS",
    GET_FUNDING_SOURCES_FAILED: "GET_FUNDING_SOURCES_FAILED",

    ADD_FUNDING_SOURCE: "ADD_FUNDING_SOURCE",
    ADD_FUNDING_SOURCE_SUCCESS: "ADD_FUNDING_SOURCE_SUCCESS",
    ADD_FUNDING_SOURCE_FAILED: "ADD_FUNDING_SOURCE_FAILED",
    ADD_FUNDING_SOURCE_RESET: "ADD_FUNDING_SOURCE_RESET",
    OPEN_ADD_FUNDING_SOURCE_MODAL: "OPEN_ADD_FUNDING_SOURCE_MODAL",
    CLOSE_ADD_FUNDING_SOURCE_MODAL: "CLOSE_ADD_FUNDING_SOURCE_MODAL",

    UPDATE_FUNDING_SOURCE: "UPDATE_FUNDING_SOURCE",
    UPDATE_FUNDING_SOURCE_SUCCESS: "UPDATE_FUNDING_SOURCE_SUCCESS",
    UPDATE_FUNDING_SOURCE_FAILED: "UPDATE_FUNDING_SOURCE_FAILED",
    UPDATE_FUNDING_SOURCE_RESET: "UPDATE_FUNDING_SOURCE_RESET",

    UPDATE_FUNDING_SOURCE_STATUS: "UPDATE_FUNDING_SOURCE_STATUS",
    UPDATE_FUNDING_SOURCE_STATUS_SUCCESS: "UPDATE_FUNDING_SOURCE_STATUS_SUCCESS",
    UPDATE_FUNDING_SOURCE_STATUS_FAILED: "UPDATE_FUNDING_SOURCE_STATUS_FAILED",
    UPDATE_FUNDING_SOURCE_STATUS_RESET: "UPDATE_FUNDING_SOURCE_STATUS_RESET",
    OPEN_UPDATE_FUNDING_SOURCE_MODAL: "OPEN_UPDATE_FUNDING_SOURCE_MODAL",
    CLOSE_UPDATE_FUNDING_SOURCE_MODAL: "CLOSE_UPDATE_FUNDING_SOURCE_MODAL",

    DELETE_FUNDING_SOURCE: "DELETE_FUNDING_SOURCE",
    DELETE_FUNDING_SOURCE_SUCCESS: "DELETE_FUNDING_SOURCE_SUCCESS",
    DELETE_FUNDING_SOURCE_FAILED: "DELETE_FUNDING_SOURCE_FAILED",
    DELETE_FUNDING_SOURCE_RESET: "DELETE_FUNDING_SOURCE_RESET",

    get_funding_sources: (query) => ({
        type: fundingSourceActions.GET_FUNDING_SOURCES,
        query,
    }),

    add_funding_source: (data) => ({
        type: fundingSourceActions.ADD_FUNDING_SOURCE,
        data,
    }),

    update_funding_source: (id, data) => ({
        type: fundingSourceActions.UPDATE_FUNDING_SOURCE,
        data,
        id,
    }),

    update_funding_source_status: (id, data) => ({
        type: fundingSourceActions.UPDATE_FUNDING_SOURCE_STATUS,
        data,
        id,
    }),

    delete_funding_source: (id) => ({
        type: fundingSourceActions.DELETE_FUNDING_SOURCE,
        id,
    }),
};

export default fundingSourceActions;
