const bulkEmailGroupAction = {
    GET_BULK_EMAIL_GROUPS: "GET_BULK_EMAIL_GROUPS",
    GET_BULK_EMAIL_GROUPS_SUCCESS: "GET_BULK_EMAIL_GROUPS_SUCCESS",
    GET_BULK_EMAIL_GROUPS_FAILED: "GET_BULK_EMAIL_GROUPS_FAILED",

    ADD_BULK_EMAIL_GROUP: "ADD_BULK_EMAIL_GROUP",
    ADD_BULK_EMAIL_GROUP_SUCCESS: "ADD_BULK_EMAIL_GROUP_SUCCESS",
    ADD_BULK_EMAIL_GROUP_FAILED: "ADD_BULK_EMAIL_GROUP_FAILED",
    ADD_BULK_EMAIL_GROUP_RESET: "ADD_BULK_EMAIL_GROUP_RESET",
    OPEN_ADD_BULK_EMAIL_GROUP_MODAL: "OPEN_ADD_BULK_EMAIL_GROUP_MODAL",
    CLOSE_ADD_BULK_EMAIL_GROUP_MODAL: "CLOSE_ADD_BULK_EMAIL_GROUP_MODAL",

    UPDATE_BULK_EMAIL_GROUP: "UPDATE_BULK_EMAIL_GROUP",
    UPDATE_BULK_EMAIL_GROUP_SUCCESS: "UPDATE_BULK_EMAIL_GROUP_SUCCESS",
    UPDATE_BULK_EMAIL_GROUP_FAILED: "UPDATE_BULK_EMAIL_GROUP_FAILED",
    UPDATE_BULK_EMAIL_GROUP_RESET: "UPDATE_BULK_EMAIL_GROUP_RESET",
    OPEN_UPDATE_BULK_EMAIL_GROUP_MODAL: "OPEN_UPDATE_BULK_EMAIL_GROUP_MODAL",
    CLOSE_UPDATE_BULK_EMAIL_GROUP_MODAL: "CLOSE_UPDATE_BULK_EMAIL_GROUP_MODAL",

    DELETE_BULK_EMAIL_GROUP: "DELETE_BULK_EMAIL_GROUP",
    DELETE_BULK_EMAIL_GROUP_SUCCESS: "DELETE_BULK_EMAIL_GROUP_SUCCESS",
    DELETE_BULK_EMAIL_GROUP_FAILED: "DELETE_BULK_EMAIL_GROUP_FAILED",
    DELETE_BULK_EMAIL_GROUP_RESET: "DELETE_BULK_EMAIL_GROUP_RESET",
};

export default bulkEmailGroupAction;
