const bulkEmailContent = {
    GET_BULK_EMAIL_CONTENTS: "GET_BULK_EMAIL_CONTENTS",
    GET_BULK_EMAIL_CONTENTS_SUCCESS: "GET_BULK_EMAIL_CONTENTS_SUCCESS",
    GET_BULK_EMAIL_CONTENTS_FAILED: "GET_BULK_EMAIL_CONTENTS_FAILED",

    ADD_BULK_EMAIL_CONTENT: "ADD_BULK_EMAIL_CONTENT",
    ADD_BULK_EMAIL_CONTENT_SUCCESS: "ADD_BULK_EMAIL_CONTENT_SUCCESS",
    ADD_BULK_EMAIL_CONTENT_FAILED: "ADD_BULK_EMAIL_CONTENT_FAILED",
    ADD_BULK_EMAIL_CONTENT_RESET: "ADD_BULK_EMAIL_CONTENT_RESET",
    OPEN_ADD_BULK_EMAIL_CONTENT_MODAL: "OPEN_ADD_BULK_EMAIL_CONTENT_MODAL",
    CLOSE_ADD_BULK_EMAIL_CONTENT_MODAL: "CLOSE_ADD_BULK_EMAIL_CONTENT_MODAL",

    UPDATE_BULK_EMAIL_CONTENT: "UPDATE_BULK_EMAIL_CONTENT",
    UPDATE_BULK_EMAIL_CONTENT_SUCCESS: "UPDATE_BULK_EMAIL_CONTENT_SUCCESS",
    UPDATE_BULK_EMAIL_CONTENT_FAILED: "UPDATE_BULK_EMAIL_CONTENT_FAILED",
    UPDATE_BULK_EMAIL_CONTENT_RESET: "UPDATE_BULK_EMAIL_CONTENT_RESET",
    OPEN_UPDATE_BULK_EMAIL_CONTENT_MODAL: "OPEN_UPDATE_BULK_EMAIL_CONTENT_MODAL",
    CLOSE_UPDATE_BULK_EMAIL_CONTENT_MODAL: "CLOSE_UPDATE_BULK_EMAIL_CONTENT_MODAL",

    VIEW_BULK_EMAIL_CONTENT: "VIEW_BULK_EMAIL_CONTENT",
    VIEW_BULK_EMAIL_CONTENT_SUCCESS: "VIEW_BULK_EMAIL_CONTENT_SUCCESS",
    VIEW_BULK_EMAIL_CONTENT_FAILED: "VIEW_BULK_EMAIL_CONTENT_FAILED",
    VIEW_BULK_EMAIL_CONTENT_RESET: "VIEW_BULK_EMAIL_CONTENT_RESET",
    OPEN_VIEW_BULK_EMAIL_CONTENT_MODAL: "OPEN_VIEW_BULK_EMAIL_CONTENT_MODAL",
    CLOSE_VIEW_BULK_EMAIL_CONTENT_MODAL: "CLOSE_VIEW_BULK_EMAIL_CONTENT_MODAL",

    UPDATE_BULK_EMAIL_CONTENT_STATUS: "UPDATE_BULK_EMAIL_CONTENT_STATUS",
    UPDATE_BULK_EMAIL_CONTENT_STATUS_SUCCESS: "UPDATE_BULK_EMAIL_CONTENT_STATUS_SUCCESS",
    UPDATE_BULK_EMAIL_CONTENT_STATUS_FAILED: "UPDATE_BULK_EMAIL_CONTENT_STATUS_FAILED",
    UPDATE_BULK_EMAIL_CONTENT_STATUS_RESET: "UPDATE_BULK_EMAIL_CONTENT_STATUS_RESET",

    DELETE_BULK_EMAIL_CONTENT: "DELETE_BULK_EMAIL_CONTENT",
    DELETE_BULK_EMAIL_CONTENT_SUCCESS: "DELETE_BULK_EMAIL_CONTENT_SUCCESS",
    DELETE_BULK_EMAIL_CONTENT_FAILED: "DELETE_BULK_EMAIL_CONTENT_FAILED",
    DELETE_BULK_EMAIL_CONTENT_RESET: "DELETE_BULK_EMAIL_CONTENT_RESET",

    SEND_BULK_EMAIL_CONTENT: "SEND_BULK_EMAIL_CONTENT",
    SEND_BULK_EMAIL_CONTENT_SUCCESS: "SEND_BULK_EMAIL_CONTENT_SUCCESS",
    SEND_BULK_EMAIL_CONTENT_FAILED: "SEND_BULK_EMAIL_CONTENT_FAILED",
    SEND_BULK_EMAIL_CONTENT_RESET: "SEND_BULK_EMAIL_CONTENT_RESET",
};

export default bulkEmailContent;
