const bulkEmailAddressAction = {
    GET_BULK_EMAIL_ADDRESSES: "GET_BULK_EMAIL_ADDRESSES",
    GET_BULK_EMAIL_ADDRESSES_SUCCESS: "GET_BULK_EMAIL_ADDRESSES_SUCCESS",
    GET_BULK_EMAIL_ADDRESSES_FAILED: "GET_BULK_EMAIL_ADDRESSES_FAILED",

    ADD_BULK_EMAIL_ADDRESS: "ADD_BULK_EMAIL_ADDRESS",
    ADD_BULK_EMAIL_ADDRESS_SUCCESS: "ADD_BULK_EMAIL_ADDRESS_SUCCESS",
    ADD_BULK_EMAIL_ADDRESS_FAILED: "ADD_BULK_EMAIL_ADDRESS_FAILED",
    ADD_BULK_EMAIL_ADDRESS_RESET: "ADD_BULK_EMAIL_ADDRESS_RESET",
    OPEN_ADD_BULK_EMAIL_ADDRESS_MODAL: "OPEN_ADD_BULK_EMAIL_ADDRESS_MODAL",
    CLOSE_ADD_BULK_EMAIL_ADDRESS_MODAL: "CLOSE_ADD_BULK_EMAIL_ADDRESS_MODAL",

    UPDATE_BULK_EMAIL_ADDRESS: "UPDATE_BULK_EMAIL_ADDRESS",
    UPDATE_BULK_EMAIL_ADDRESS_SUCCESS: "UPDATE_BULK_EMAIL_ADDRESS_SUCCESS",
    UPDATE_BULK_EMAIL_ADDRESS_FAILED: "UPDATE_BULK_EMAIL_ADDRESS_FAILED",
    UPDATE_BULK_EMAIL_ADDRESS_RESET: "UPDATE_BULK_EMAIL_ADDRESS_RESET",
    OPEN_UPDATE_BULK_EMAIL_ADDRESS_MODAL: "OPEN_UPDATE_BULK_EMAIL_ADDRESS_MODAL",
    CLOSE_UPDATE_BULK_EMAIL_ADDRESS_MODAL: "CLOSE_UPDATE_BULK_EMAIL_ADDRESS_MODAL",

    UPDATE_BULK_EMAIL_ADDRESS_STATUS: "UPDATE_BULK_EMAIL_ADDRESS_STATUS",
    UPDATE_BULK_EMAIL_ADDRESS_STATUS_SUCCESS: "UPDATE_BULK_EMAIL_ADDRESS_STATUS_SUCCESS",
    UPDATE_BULK_EMAIL_ADDRESS_STATUS_FAILED: "UPDATE_BULK_EMAIL_ADDRESS_STATUS_FAILED",
    UPDATE_BULK_EMAIL_ADDRESS_STATUS_RESET: "UPDATE_BULK_EMAIL_ADDRESS_STATUS_RESET",

    DELETE_BULK_EMAIL_ADDRESS: "DELETE_BULK_EMAIL_ADDRESS",
    DELETE_BULK_EMAIL_ADDRESS_SUCCESS: "DELETE_BULK_EMAIL_ADDRESS_SUCCESS",
    DELETE_BULK_EMAIL_ADDRESS_FAILED: "DELETE_BULK_EMAIL_ADDRESS_FAILED",
    DELETE_BULK_EMAIL_ADDRESS_RESET: "DELETE_BULK_EMAIL_ADDRESS_RESET",

    IMPORT_BULK_EMAIL_ADDRESS: "IMPORT_BULK_EMAIL_ADDRESS",
    IMPORT_BULK_EMAIL_ADDRESS_SUCCESS: "IMPORT_BULK_EMAIL_ADDRESS_SUCCESS",
    IMPORT_BULK_EMAIL_ADDRESS_FAILED: "IMPORT_BULK_EMAIL_ADDRESS_FAILED",
    IMPORT_BULK_EMAIL_ADDRESS_RESET: "IMPORT_BULK_EMAIL_ADDRESS_RESET",
    OPEN_IMPORT_BULK_EMAIL_ADDRESS_MODAL: "OPEN_IMPORT_BULK_EMAIL_ADDRESS_MODAL",
    CLOSE_IMPORT_BULK_EMAIL_ADDRESS_MODAL: "CLOSE_IMPORT_BULK_EMAIL_ADDRESS_MODAL",
    RESET_IMPORT_BULK_EMAIL_ADDRESS_VALIDATE: "RESET_IMPORT_BULK_EMAIL_ADDRESS_VALIDATE",

    IMPORT_CONFIRM_BULK_EMAIL_ADDRESS: "IMPORT_CONFIRM_BULK_EMAIL_ADDRESS",
    IMPORT_CONFIRM_BULK_EMAIL_ADDRESS_SUCCESS: "IMPORT_CONFIRM_BULK_EMAIL_ADDRESS_SUCCESS",
    IMPORT_CONFIRM_BULK_EMAIL_ADDRESS_FAILED: "IMPORT_CONFIRM_BULK_EMAIL_ADDRESS_FAILED",
    IMPORT_CONFIRM_BULK_EMAIL_ADDRESS_RESET: "IMPORT_CONFIRM_BULK_EMAIL_ADDRESS_RESET",
};

export default bulkEmailAddressAction;
