const bulkEmailCredentialAction = {
    GET_BULK_EMAIL_CREDENTIAL: "GET_BULK_EMAIL_CREDENTIAL",
    GET_BULK_EMAIL_CREDENTIAL_SUCCESS: "GET_BULK_EMAIL_CREDENTIAL_SUCCESS",
    GET_BULK_EMAIL_CREDENTIAL_FAILED: "GET_BULK_EMAIL_CREDENTIAL_FAILED",

    UPDATE_BULK_EMAIL_CREDENTIAL: "UPDATE_BULK_EMAIL_CREDENTIAL",
    UPDATE_BULK_EMAIL_CREDENTIAL_SUCCESS: "UPDATE_BULK_EMAIL_CREDENTIAL_SUCCESS",
    UPDATE_BULK_EMAIL_CREDENTIAL_FAILED: "UPDATE_BULK_EMAIL_CREDENTIAL_FAILED",
    UPDATE_BULK_EMAIL_CREDENTIAL_RESET: "UPDATE_BULK_EMAIL_CREDENTIAL_RESET",
};

export default bulkEmailCredentialAction;
