const actions = {
    GET_TRANSACTION_REMARKS: "   GET_TRANSACTION_REMARKS",
    GET_TRANSACTION_REMARKS_SUCCESS: "   GET_TRANSACTION_REMARKS_SUCCESS",
    GET_TRANSACTION_REMARKS_FAILED: "    GET_TRANSACTION_REMARKS_FAILED",
    GET_TRANSACTION_REMARKS_RESET: "     GET_TRANSACTION_REMARKS_RESET",

    GET_TRANSACTION_REMARKS_BYID: "  GET_TRANSACTION_REMARKS_BYID",
    GET_TRANSACTION_REMARKS_BYID_SUCCESS:
        "  GET_TRANSACTION_REMARKS_BYID_SUCCESS",
    GET_TRANSACTION_REMARKS_BYID_FAILED:
        "   GET_TRANSACTION_REMARKS_BYID_FAILED",
    GET_TRANSACTION_REMARKS_BYID_RESET:
        "    GET_TRANSACTION_REMARKS_BYID_RESET",

    CREATE_TRANSACTION_REMARKS: "CREATE_TRANSACTION_REMARKS",
    CREATE_TRANSACTION_REMARKS_SUCCESS: "CREATE_TRANSACTION_REMARKS_SUCCESS",
    CREATE_TRANSACTION_REMARKS_FAILED: "CREATE_TRANSACTION_REMARKS_FAILED",
    CREATE_TRANSACTION_REMARKS_RESET: "CREATE_TRANSACTION_REMARKS_RESET",

    get_transaction_remarks: (transaction_id, query) => ({
        type: actions.GET_TRANSACTION_REMARKS,
        transaction_id,
        query,
    }),

    get_transaction_remarks_byid: (id) => ({
        type: actions.GET_TRANSACTION_REMARKS_BYID,
        id,
    }),

    create_transaction_remarks: (transaction_id, data) => ({
        type: actions.CREATE_TRANSACTION_REMARKS,
        transaction_id,
        data,
    }),
};

export default actions;
