const actions = {
    GET_LANGUAGE_OPTION: "GET_LANGUAGE_OPTION",
    GET_LANGUAGE_OPTION_SUCCESS: "GET_LANGUAGE_OPTION_SUCCESS",
    GET_LANGUAGE_OPTION_FAILED: "GET_LANGUAGE_OPTION_FAILED",
    GET_LANGUAGE_OPTION_DETAILS: "GET_LANGUAGE_OPTION_DETAILS",
    GET_LANGUAGE_OPTION_DETAILS_SUCCESS: "GET_LANGUAGE_OPTION_DETAILS_SUCCESS",
    GET_LANGUAGE_OPTION_DETAILS_FAILED: "GET_LANGUAGE_OPTION_DETAILS_FAILED",

    ADD_LANGUAGE_OPTION: "ADD_LANGUAGE_OPTION",
    ADD_LANGUAGE_OPTION_SUCCESS: "ADD_LANGUAGE_OPTION_SUCCESS",
    ADD_LANGUAGE_OPTION_FAILED: "ADD_LANGUAGE_OPTION_FAILED",
    ADD_LANGUAGE_OPTION_RESET: "ADD_LANGUAGE_OPTION_RESET",

    UPDATE_LANGUAGE_OPTION: "UPDATE_LANGUAGE_OPTION",
    UPDATE_LANGUAGE_OPTION_SUCCESS: "UPDATE_LANGUAGE_OPTION_SUCCESS",
    UPDATE_LANGUAGE_OPTION_FAILED: "UPDATE_LANGUAGE_OPTION_FAILED",
    UPDATE_LANGUAGE_OPTION_RESET: "UPDATE_LANGUAGE_OPTION_RESET",

    UPDATE_LANGUAGE_OPTION_STATUS: "UPDATE_LANGUAGE_OPTION_STATUS",
    UPDATE_LANGUAGE_OPTION_STATUS_SUCCESS: "UPDATE_LANGUAGE_OPTION_STATUS_SUCCESS",
    UPDATE_LANGUAGE_OPTION_STATUS_FAILED: "UPDATE_LANGUAGE_OPTION_STATUS_FAILED",
    UPDATE_LANGUAGE_OPTION_STATUS_RESET: "UPDATE_LANGUAGE_OPTION_STATUS_RESET",

    DELETE_LANGUAGE_OPTION: "DELETE_LANGUAGE_OPTION",
    DELETE_LANGUAGE_OPTION_SUCCESS: "DELETE_LANGUAGE_OPTION_SUCCESS",
    DELETE_LANGUAGE_OPTION_FAILED: "DELETE_LANGUAGE_OPTION_FAILED",
    DELETE_LANGUAGE_OPTION_RESET: "DELETE_LANGUAGE_OPTION_RESET",

    get_all_language_option: (query) => ({
        type: actions.GET_LANGUAGE_OPTION,
        query,
    }),

    get_language_option_details: (id) => ({
        tlanguage_optionype: actions.GET_LANGUAGE_OPTION_DETAILS,
        id,
    }),

    add_language_option: (data) => ({
        type: actions.ADD_LANGUAGE_OPTION,
        data,
    }),

    update_language_option: (id, data) => ({
        type: actions.UPDATE_LANGUAGE_OPTION,
        data,
        id,
    }),

    update_language_option_status: (id, data) => ({
        type: actions.UPDATE_LANGUAGE_OPTION_STATUS,
        data,
        id,
    }),

    delete_language_option: (id) => ({
        type: actions.DELETE_LANGUAGE_OPTION,
        id,
    }),
};

export default actions;
