const actions = {
    GET_CUSTOMER_COUNT_BY_DEVICE_TYPE: "GET_CUSTOMER_COUNT_BY_DEVICE_TYPE",
    GET_CUSTOMER_COUNT_BY_DEVICE_TYPE_SUCCESS: "GET_CUSTOMER_COUNT_BY_DEVICE_TYPE_SUCCESS",
    GET_CUSTOMER_COUNT_BY_DEVICE_TYPE_FAILED: "GET_CUSTOMER_COUNT_BY_DEVICE_TYPE_FAILED",

    GET_CUSTOMER_KYC_COUNT_BY_STATUS: "GET_CUSTOMER_KYC_COUNT_BY_STATUS",
    GET_CUSTOMER_KYC_COUNT_BY_STATUS_SUCCESS: "GET_CUSTOMER_KYC_COUNT_BY_STATUS_SUCCESS",
    GET_CUSTOMER_KYC_COUNT_BY_STATUS_FAILED: "GET_CUSTOMER_KYC_COUNT_BY_STATUS_FAILED",

    GET_CUSTOMER_KYC_COUNT_BY_STATUS_PREVIOUS: "GET_CUSTOMER_KYC_COUNT_BY_STATUS_PREVIOUS",
    GET_CUSTOMER_KYC_COUNT_BY_STATUS_PREVIOUS_SUCCESS: "GET_CUSTOMER_KYC_COUNT_BY_STATUS_PREVIOUS_SUCCESS",
    GET_CUSTOMER_KYC_COUNT_BY_STATUS_PREVIOUS_FAILED: "GET_CUSTOMER_KYC_COUNT_BY_STATUS_PREVIOUS_FAILED",

    GET_TRANSACTION_COUNT_BY_STATUS: "GET_TRANSACTION_COUNT_BY_STATUS",
    GET_TRANSACTION_COUNT_BY_STATUS_SUCCESS: "GET_TRANSACTION_COUNT_BY_STATUS_SUCCESS",
    GET_TRANSACTION_COUNT_BY_STATUS_FAILED: "GET_TRANSACTION_COUNT_BY_STATUS_FAILED",

    CHANGE_DASHBOARD_FILTER_PARAMS: "CHANGE_DASHBOARD_FILTER_PARAMS",

    get_customer_count_by_device_type: (query) => ({
        type: actions.GET_CUSTOMER_COUNT_BY_DEVICE_TYPE,
        query,
    }),

    get_customer_kyc_count_by_status: (query) => ({
        type: actions.GET_CUSTOMER_KYC_COUNT_BY_STATUS,
        query,
    }),

    get_customer_kyc_count_by_status_previous: (query) => ({
        type: actions.GET_CUSTOMER_KYC_COUNT_BY_STATUS_PREVIOUS,
        query,
    }),

    get_transaction_count_by_status: (query) => ({
        type: actions.GET_TRANSACTION_COUNT_BY_STATUS,
        query,
    }),

    change_dashboard_filter_params: (query) => ({
        type: actions.CHANGE_DASHBOARD_FILTER_PARAMS,
        query,
    }),
};

export default actions;
