const emailTemplateActions = {
    GET_EMAIL_TEMPLATE: "GET_EMAIL_TEMPLATE",
    GET_EMAIL_TEMPLATE_SUCCESS: "GET_EMAIL_TEMPLATE_SUCCESS",
    GET_EMAIL_TEMPLATE_FAILURE: "GET_EMAIL_TEMPLATE_FAILURE",

    GET_EMAIL_TEMPLATE_TAG: "GET_EMAIL_TEMPLATE_TAG",
    GET_EMAIL_TEMPLATE_TAG_SUCCESS: "GET_EMAIL_TEMPLATE_TAG_SUCCESS",
    GET_EMAIL_TEMPLATE_TAG_FAILURE: "GET_EMAIL_TEMPLATE_TAG_FAILURE",

    ADD_EMAIL_TEMPLATE: "ADD_EMAIL_TEMPLATE",
    ADD_EMAIL_TEMPLATE_SUCCESS: "ADD_EMAIL_TEMPLATE_SUCCESS",
    ADD_EMAIL_TEMPLATE_FAILURE: "ADD_EMAIL_TEMPLATE_FAILURE",
    ADD_EMAIL_TEMPLATE_RESET: "ADD_EMAIL_TEMPLATE_RESET",
    OPEN_ADD_EMAIL_TEMPLATE_MODAL: "OPEN_ADD_EMAIL_TEMPLATE_MODAL",
    CLOSE_ADD_EMAIL_TEMPLATE_MODAL: "CLOSE_ADD_EMAIL_TEMPLATE_MODAL",

    UPDATE_EMAIL_TEMPLATE: "UPDATE_EMAIL_TEMPLATE",
    UPDATE_EMAIL_TEMPLATE_SUCCESS: "UPDATE_EMAIL_TEMPLATE_SUCCESS",
    UPDATE_EMAIL_TEMPLATE_FAILURE: "UPDATE_EMAIL_TEMPLATE_FAILURE",
    UPDATE_EMAIL_TEMPLATE_RESET: "UPDATE_EMAIL_TEMPLATE_RESET",

    OPEN_UPDATE_EMAIL_TEMPLATE_MODAL: "OPEN_UPDATE_EMAIL_TEMPLATE_MODAL",
    CLOSE_UPDATE_EMAIL_TEMPLATE_MODAL: "CLOSE_UPDATE_EMAIL_TEMPLATE_MODAL",

    get_email_templates: (query) => ({
        type: emailTemplateActions.GET_EMAIL_TEMPLATE,
        query,
    }),

    get_email_template_tags: (query) => ({
        type: emailTemplateActions.GET_EMAIL_TEMPLATE_TAG,
        query,
    }),

    add_email_template: (data) => ({
        type: emailTemplateActions.ADD_EMAIL_TEMPLATE,
        data,
    }),

    update_email_template: (id, data) => ({
        type: emailTemplateActions.UPDATE_EMAIL_TEMPLATE,
        data,
        id,
    }),
};

export default emailTemplateActions;
