const actions = {
    GET_LANGUAGE_COUNTRY: "GET_LANGUAGE_COUNTRY",
    GET_LANGUAGE_COUNTRY_SUCCESS: "GET_LANGUAGE_COUNTRY_SUCCESS",
    GET_LANGUAGE_COUNTRY_FAILED: "GET_LANGUAGE_COUNTRY_FAILED",
    GET_LANGUAGE_COUNTRY_DETAILS: "GET_LANGUAGE_COUNTRY_DETAILS",
    GET_LANGUAGE_COUNTRY_DETAILS_SUCCESS: "GET_LANGUAGE_COUNTRY_DETAILS_SUCCESS",
    GET_LANGUAGE_COUNTRY_DETAILS_FAILED: "GET_LANGUAGE_COUNTRY_DETAILS_FAILED",

    ADD_LANGUAGE_COUNTRY: "ADD_LANGUAGE_COUNTRY",
    ADD_LANGUAGE_COUNTRY_SUCCESS: "ADD_LANGUAGE_COUNTRY_SUCCESS",
    ADD_LANGUAGE_COUNTRY_FAILED: "ADD_LANGUAGE_COUNTRY_FAILED",
    ADD_LANGUAGE_COUNTRY_RESET: "ADD_LANGUAGE_COUNTRY_RESET",

    UPDATE_LANGUAGE_COUNTRY: "UPDATE_LANGUAGE_COUNTRY",
    UPDATE_LANGUAGE_COUNTRY_SUCCESS: "UPDATE_LANGUAGE_COUNTRY_SUCCESS",
    UPDATE_LANGUAGE_COUNTRY_FAILED: "UPDATE_LANGUAGE_COUNTRY_FAILED",
    UPDATE_LANGUAGE_COUNTRY_RESET: "UPDATE_LANGUAGE_COUNTRY_RESET",

    UPDATE_LANGUAGE_COUNTRY_STATUS: "UPDATE_LANGUAGE_COUNTRY_STATUS",
    UPDATE_LANGUAGE_COUNTRY_STATUS_SUCCESS: "UPDATE_LANGUAGE_COUNTRY_STATUS_SUCCESS",
    UPDATE_LANGUAGE_COUNTRY_STATUS_FAILED: "UPDATE_LANGUAGE_COUNTRY_STATUS_FAILED",
    UPDATE_LANGUAGE_COUNTRY_STATUS_RESET: "UPDATE_LANGUAGE_COUNTRY_STATUS_RESET",

    DELETE_LANGUAGE_COUNTRY: "DELETE_LANGUAGE_COUNTRY",
    DELETE_LANGUAGE_COUNTRY_SUCCESS: "DELETE_LANGUAGE_COUNTRY_SUCCESS",
    DELETE_LANGUAGE_COUNTRY_FAILED: "DELETE_LANGUAGE_COUNTRY_FAILED",
    DELETE_LANGUAGE_COUNTRY_RESET: "DELETE_LANGUAGE_COUNTRY_RESET",

    get_all_language_country: (query) => ({
        type: actions.GET_LANGUAGE_COUNTRY,
        query,
    }),

    get_language_country_details: (id) => ({
        tlanguage_COUNTRYype: actions.GET_LANGUAGE_COUNTRY_DETAILS,
        id,
    }),

    add_language_country: (data) => ({
        type: actions.ADD_LANGUAGE_COUNTRY,
        data,
    }),

    update_language_country: (id, data) => ({
        type: actions.UPDATE_LANGUAGE_COUNTRY,
        data,
        id,
    }),

    update_language_country_status: (id, data) => ({
        type: actions.UPDATE_LANGUAGE_COUNTRY_STATUS,
        data,
        id,
    }),

    delete_language_country: (id) => ({
        type: actions.DELETE_LANGUAGE_COUNTRY,
        id,
    }),
};

export default actions;
