const referenceTypeId = {
    designations: 101,
    identityTypes: 2,
    sourceOfIncomes: 6,
    remittancePurposes: 7,
    transactionStatus: 66,
    businessTypes: 146,
    kycStatuses: 21,
    emailTemplateTypeForCustomer: 150,
    emailTemplateTypeForAdmin: 151,
    emailTemplateTypeForAdminToCustomer: 149,
    paymentType: 1,
    kycDocuments: 2,
    kybDocuments: 153,
    kybKycStatuses: 152,
    genders: 42,
    occupations: 17,
    partnerTypes: 3,
    rdfiReturnCodes: 270,
    relations: 18,
    balanceRequestStatus: 67,
    emailConfigFor: 10,
};

export default referenceTypeId;
