const actions = {
    GET_PAYOUT_LOCATION: "GET_PAYOUT_LOCATION",
    GET_PAYOUT_LOCATION_SUCCESS: "GET_PAYOUT_LOCATION_SUCCESS",
    GET_PAYOUT_LOCATION_FAILED: "GET_PAYOUT_LOCATION_FAILED",

    GET_PAYOUT_LOCATION_DETAILS: "GET_PAYOUT_LOCATION_DETAILS",
    GET_PAYOUT_LOCATION_DETAILS_SUCCESS: "GET_PAYOUT_LOCATION_DETAILS_SUCCESS",
    GET_PAYOUT_LOCATION_DETAILS_FAILED: "GET_PAYOUT_LOCATION_DETAILS_FAILED",
    OPEN_GET_PAYOUT_LOCATION_DETAILS_MODAL: "OPEN_GET_PAYOUT_LOCATION_DETAILS_MODAL",
    CLOSE_GET_PAYOUT_LOCATION_DETAILS_MODAL: "CLOSE_GET_PAYOUT_LOCATION_DETAILS_MODAL",
    GET_PAYOUT_LOCATION_DETAILS_RESET: "GET_PAYOUT_LOCATION_DETAILS_RESET",

    ADD_PAYOUT_LOCATION: "ADD_PAYOUT_LOCATION",
    ADD_PAYOUT_LOCATION_SUCCESS: "ADD_PAYOUT_LOCATION_SUCCESS",
    ADD_PAYOUT_LOCATION_FAILED: "ADD_PAYOUT_LOCATION_FAILED",
    ADD_PAYOUT_LOCATION_RESET: "ADD_PAYOUT_LOCATION_RESET",

    UPDATE_PAYOUT_LOCATION: "UPDATE_PAYOUT_LOCATION",
    UPDATE_PAYOUT_LOCATION_SUCCESS: "UPDATE_PAYOUT_LOCATION_SUCCESS",
    UPDATE_PAYOUT_LOCATION_FAILED: "UPDATE_PAYOUT_LOCATION_FAILED",
    UPDATE_PAYOUT_LOCATION_RESET: "UPDATE_PAYOUT_LOCATION_RESET",

    UPDATE_PAYOUT_LOCATION_STATUS: "UPDATE_PAYOUT_LOCATION_STATUS",
    UPDATE_PAYOUT_LOCATION_STATUS_SUCCESS: "UPDATE_PAYOUT_LOCATION_STATUS_SUCCESS",
    UPDATE_PAYOUT_LOCATION_STATUS_FAILED: "UPDATE_PAYOUT_LOCATION_STATUS_FAILED",

    DELETE_PAYOUT_LOCATION: "DELETE_PAYOUT_LOCATION",
    DELETE_PAYOUT_LOCATION_SUCCESS: "DELETE_PAYOUT_LOCATION_SUCCESS",
    DELETE_PAYOUT_LOCATION_FAILED: "DELETE_PAYOUT_LOCATION_FAILED",
    DELETE_PAYOUT_LOCATION_RESET: "DELETE_PAYOUT_LOCATION_RESET",

    get_all_payout_location: (query) => ({
        type: actions.GET_PAYOUT_LOCATION,
        query,
    }),

    get_payout_location_details: (id) => ({
        type: actions.GET_PAYOUT_LOCATION_DETAILS,
        id,
    }),

    add_payout_location: (data) => ({
        type: actions.ADD_PAYOUT_LOCATION,
        data,
    }),

    update_payout_location: (id, data) => ({
        type: actions.UPDATE_PAYOUT_LOCATION,
        id,
        data,
    }),

    update_payout_location_status: (id, data) => ({
        type: actions.UPDATE_PAYOUT_LOCATION_STATUS,
        data,
        id,
    }),

    delete_payout_location: (id) => ({
        type: actions.DELETE_PAYOUT_LOCATION,
        id,
    }),

    close_get_payout_location_details_modal: () => ({
        type: actions.CLOSE_GET_PAYOUT_LOCATION_DETAILS_MODAL,
    }),
};

export default actions;
