const actions = {
    GET_ACH_RDFI_WEBHOOKS: "GET_ACH_RDFI_WEBHOOKS",
    GET_ACH_RDFI_WEBHOOKS_SUCCESS: "GET_ACH_RDFI_WEBHOOKS_SUCCESS",
    GET_ACH_RDFI_WEBHOOKS_FAILED: "GET_ACH_RDFI_WEBHOOKS_FAILED",
    GET_ACH_RDFI_WEBHOOKS_RESET: "GET_ACH_RDFI_WEBHOOKS_RESET",

    GET_ACH_CIR_WEBHOOKS: "GET_ACH_CIR_WEBHOOKS",
    GET_ACH_CIR_WEBHOOKS_SUCCESS: "GET_ACH_CIR_WEBHOOKS_SUCCESS",
    GET_ACH_CIR_WEBHOOKS_FAILED: "GET_ACH_CIR_WEBHOOKS_FAILED",
    GET_ACH_CIR_WEBHOOKS_RESET: "GET_ACH_CIR_WEBHOOKS_RESET",

    GET_ACH_RETURN_WEBHOOKS: "GET_ACH_RETURN_WEBHOOKS",
    GET_ACH_RETURN_WEBHOOKS_SUCCESS: "GET_ACH_RETURN_WEBHOOKS_SUCCESS",
    GET_ACH_RETURN_WEBHOOKS_FAILED: "GET_ACH_RETURN_WEBHOOKS_FAILED",
    GET_ACH_RETURN_WEBHOOKS_RESET: "GET_ACH_RETURN_WEBHOOKS_RESET",

    GET_ACH_REJECT_WEBHOOKS: "GET_ACH_REJECT_WEBHOOKS",
    GET_ACH_REJECT_WEBHOOKS_SUCCESS: "GET_ACH_REJECT_WEBHOOKS_SUCCESS",
    GET_ACH_REJECT_WEBHOOKS_FAILED: "GET_ACH_REJECT_WEBHOOKS_FAILED",
    GET_ACH_REJECT_WEBHOOKS_RESET: "GET_ACH_REJECT_WEBHOOKS_RESET",

    get_ach_rdfi_webhooks: (query) => ({
        type: actions.GET_ACH_RDFI_WEBHOOKS,
        query,
    }),

    get_ach_cir_webhooks: (query) => ({
        type: actions.GET_ACH_CIR_WEBHOOKS,
        query,
    }),

    get_ach_return_webhooks: (query) => ({
        type: actions.GET_ACH_RETURN_WEBHOOKS,
        query,
    }),

    get_ach_reject_webhooks: (query) => ({
        type: actions.GET_ACH_REJECT_WEBHOOKS,
        query,
    }),
};

export default actions;
