const customerActions = {
    UPDATE_CUSTOMER_ACCOUNT: "UPDATE_CUSTOMER_ACCOUNT",
    UPDATE_CUSTOMER_ACCOUNT_SUCCESS: "UPDATE_CUSTOMER_ACCOUNT_SUCCESS",
    UPDATE_CUSTOMER_ACCOUNT_FAILED: "UPDATE_CUSTOMER_ACCOUNT_FAILED",
    UPDATE_CUSTOMER_ACCOUNT_RESET: "UPDATE_CUSTOMER_ACCOUNT_RESET",
    OPEN_UPDATE_CUSTOMER_ACCOUNT_MODAL: "OPEN_UPDATE_CUSTOMER_ACCOUNT_MODAL",
    CLOSE_UPDATE_CUSTOMER_ACCOUNT_MODAL: "CLOSE_UPDATE_CUSTOMER_ACCOUNT_MODAL",
};

export default customerActions;
