const actions = {
    GET_TRANSACTION_DETAILS: "GET_TRANSACTION_DETAILS",
    GET_TRANSACTION_DETAILS_SUCCESS: "GET_TRANSACTION_DETAILS_SUCCESS",
    GET_TRANSACTION_DETAILS_FAILED: "GET_TRANSACTION_DETAILS_FAILED",
    GET_TRANSACTION_DETAILS_RESET: "GET_TRANSACTION_DETAILS_RESET",

    GET_TRANSACTION_REFUND_BLOCK: "GET_TRANSACTION_REFUND_BLOCK",
    GET_TRANSACTION_REFUND_BLOCK_SUCCESS:
        "GET_TRANSACTION_REFUND_BLOCK_SUCCESS",
    GET_TRANSACTION_REFUND_BLOCK_FAILED: "GET_TRANSACTION_REFUND_BLOCK_FAILED",
    GET_TRANSACTION_REFUND_BLOCK_RESET: "GET_TRANSACTION_REFUND_BLOCK_RESET",

    GET_PENDING_PAYMENT: "GET_PENDING_PAYMENT",
    GET_PENDING_PAYMENT_SUCCESS: "GET_PENDING_PAYMENT_SUCCESS",
    GET_PENDING_PAYMENT_FAILED: "GET_PENDING_PAYMENT_FAILED",

    RELEASE_PENDING_PAYMENT: "RELEASE_PENDING_PAYMENT",
    RELEASE_PENDING_PAYMENT_SUCCESS: "RELEASE_PENDING_PAYMENT_SUCCESS",
    RELEASE_PENDING_PAYMENT_FAILED: "RELEASE_PENDING_PAYMENT_FAILED",
    RELEASE_PENDING_PAYMENT_RESET: "RELEASE_PENDING_PAYMENT_RESET",

    GET_PENDING_TRANSACTIONS: "GET_PENDING_TRANSACTIONS",
    GET_PENDING_TRANSACTIONS_SUCCESS: "GET_PENDING_TRANSACTIONS_SUCCESS",
    GET_PENDING_TRANSACTIONS_FAILED: "GET_PENDING_TRANSACTIONS_FAILED",

    RELEASE_PENDING_TRANSACTIONS: "RELEASE_PENDING_TRANSACTIONS",
    RELEASE_PENDING_TRANSACTIONS_SUCCESS:
        "RELEASE_PENDING_TRANSACTIONS_SUCCESS",
    RELEASE_PENDING_TRANSACTIONS_FAILED: "RELEASE_PENDING_TRANSACTIONS_FAILED",
    RELEASE_PENDING_TRANSACTIONS_RESET: "RELEASE_PENDING_TRANSACTIONS_RESET",

    GET_BLOCKED_TRANSACTIONS: "GET_BLOCKED_TRANSACTIONS",
    GET_BLOCKED_TRANSACTIONS_SUCCESS: "GET_BLOCKED_TRANSACTIONS_SUCCESS",
    GET_BLOCKED_TRANSACTIONS_FAILED: "GET_BLOCKED_TRANSACTIONS_FAILED",

    BLOCK_TRANSACTIONS: "BLOCK_TRANSACTIONS",
    BLOCK_TRANSACTIONS_SUCCESS: "BLOCK_TRANSACTIONS_SUCCESS",
    BLOCK_TRANSACTIONS_FAILED: "BLOCK_TRANSACTIONS_FAILED",
    BLOCK_TRANSACTIONS_RESET: "BLOCK_TRANSACTIONS_RESET",

    REFUND_TRANSACTIONS: "REFUND_TRANSACTIONS",
    REFUND_TRANSACTIONS_SUCCESS: "REFUND_TRANSACTIONS_SUCCESS",
    REFUND_TRANSACTIONS_FAILED: "REFUND_TRANSACTIONS_FAILED",
    REFUND_TRANSACTIONS_RESET: "REFUND_TRANSACTIONS_RESET",

    RELEASE_BLOCKED_TRANSACTIONS: "RELEASE_BLOCKED_TRANSACTIONS",
    RELEASE_BLOCKED_TRANSACTIONS_SUCCESS:
        "RELEASE_BLOCKED_TRANSACTIONS_SUCCESS",
    RELEASE_BLOCKED_TRANSACTIONS_FAILED: "RELEASE_BLOCKED_TRANSACTIONS_FAILED",
    RELEASE_BLOCKED_TRANSACTIONS_RESET: "RELEASE_BLOCKED_TRANSACTIONS_RESET",

    GET_AML_SUSPICIOUS: "GET_AML_SUSPICIOUS",
    GET_AML_SUSPICIOUS_SUCCESS: "GET_AML_SUSPICIOUS_SUCCESS",
    GET_AML_SUSPICIOUS_FAILED: "GET_AML_SUSPICIOUS_FAILED",

    RELEASE_AML_SUSPICIOUS: "RELEASE_AML_SUSPICIOUS",
    RELEASE_AML_SUSPICIOUS_SUCCESS: "RELEASE_AML_SUSPICIOUS_SUCCESS",
    RELEASE_AML_SUSPICIOUS_FAILED: "RELEASE_AML_SUSPICIOUS_FAILED",
    RELEASE_AML_SUSPICIOUS_RESET: "RELEASE_AML_SUSPICIOUS_RESET",

    GET_EXCEPTION_TRANSACTIONS: "GET_EXCEPTION_TRANSACTIONS",
    GET_EXCEPTION_TRANSACTIONS_SUCCESS: "GET_EXCEPTION_TRANSACTIONS_SUCCESS",
    GET_EXCEPTION_TRANSACTIONS_FAILED: "GET_EXCEPTION_TRANSACTIONS_FAILED",

    RELEASE_EXCEPTION_TRANSACTIONS: "RELEASE_EXCEPTION_TRANSACTIONS",
    RELEASE_EXCEPTION_TRANSACTIONS_SUCCESS:
        "RELEASE_EXCEPTION_TRANSACTIONS_SUCCESS",
    RELEASE_EXCEPTION_TRANSACTIONS_FAILED:
        "RELEASE_EXCEPTION_TRANSACTIONS_FAILED",
    RELEASE_EXCEPTION_TRANSACTIONS_RESET:
        "RELEASE_EXCEPTION_TRANSACTIONS_RESET",

    //FETCH
    get_transaction_details: (id) => ({
        type: actions.GET_TRANSACTION_DETAILS,
        id,
    }),

    get_transaction_refund_block: (query) => ({
        type: actions.GET_TRANSACTION_REFUND_BLOCK,
        query,
    }),

    get_payment_pending: (query) => ({
        type: actions.GET_PENDING_PAYMENT,
        query,
    }),

    get_pending_transactions: (query) => ({
        type: actions.GET_PENDING_TRANSACTIONS,
        query,
    }),

    get_blocked_transactions: (query) => ({
        type: actions.GET_BLOCKED_TRANSACTIONS,
        query,
    }),

    get_aml_suspicious: (query) => ({
        type: actions.GET_AML_SUSPICIOUS,
        query,
    }),

    get_exception_transactions: (query) => ({
        type: actions.GET_EXCEPTION_TRANSACTIONS,
        query,
    }),

    //update
    update_payment_pending: (id, data) => ({
        type: actions.RELEASE_PENDING_PAYMENT,
        data,
        id,
    }),
    update_pending_transactions: (id) => ({
        type: actions.RELEASE_PENDING_TRANSACTIONS,
        id,
    }),
    block_transactions: (id, data) => ({
        type: actions.BLOCK_TRANSACTIONS,
        data,
        id,
    }),
    refund_transactions: (id, data) => ({
        type: actions.REFUND_TRANSACTIONS,
        data,
        id,
    }),
    update_blocked_transactions: (id, data) => ({
        type: actions.RELEASE_BLOCKED_TRANSACTIONS,
        data,
        id,
    }),
    update_aml_suspicious: (id, data) => ({
        type: actions.RELEASE_AML_SUSPICIOUS,
        data,
        id,
    }),
    update_exception_transactions: (id, data) => ({
        type: actions.RELEASE_EXCEPTION_TRANSACTIONS,
        data,
        id,
    }),
};

export default actions;
