const actions = {
    GET_ATTACHMENT: "GET_ATTACHMENT",
    GET_ATTACHMENT_SUCCESS: "GET_ATTACHMENT_SUCCESS",
    GET_ATTACHMENT_FAILURE: "GET_ATTACHMENT_FAILURE",
    GET_ATTACHMENT_RESET: "GET_ATTACHMENT_RESET",

    UPLOAD_ATTACHMENT: "UPLOAD_ATTACHMENT",
    UPLOAD_ATTACHMENT_SUCCESS: "UPLOAD_ATTACHMENT_SUCCESS",
    UPLOAD_ATTACHMENT_FAILURE: "UPLOAD_ATTACHMENT_FAILURE",
    UPLOAD_ATTACHMENT_RESET: "UPLOAD_ATTACHMENT_RESET",

    get_all_attachments: (query) => ({ type: actions.GET_ATTACHMENT, query }),

    upload_attachment: (data) => ({ type: actions.UPLOAD_ATTACHMENT, data }),
};

export default actions;
