const actions = {
    GET_PAYMENT_RULES: "GET_PAYMENT_RULES",
    GET_PAYMENT_RULES_SUCCESS: "GET_PAYMENT_RULES_SUCCESS",
    GET_PAYMENT_RULES_FAILED: "GET_PAYMENT_RULES_FAILED",

    GET_PAYMENT_RULES_DETAILS_BY_ID: "GET_PAYMENT_RULES_DETAILS_BY_ID",
    GET_PAYMENT_RULES_DETAILS_BY_ID_SUCCESS:
        "GET_PAYMENT_RULES_DETAILS_BY_ID_SUCCESS",
    GET_PAYMENT_RULES_DETAILS_BY_ID_FAILED:
        "GET_PAYMENT_RULES_DETAILS_BY_ID_FAILED",

    ADD_PAYMENT_RULES: "ADD_PAYMENT_RULES",
    ADD_PAYMENT_RULES_SUCCESS: "ADD_PAYMENT_RULES_SUCCESS",
    ADD_PAYMENT_RULES_FAILED: "ADD_PAYMENT_RULES_FAILED",
    ADD_PAYMENT_RULES_RESET: "ADD_PAYMENT_RULES_RESET",

    UPDATE_PAYMENT_RULES: "UPDATE_PAYMENT_RULES",
    UPDATE_PAYMENT_RULES_SUCCESS: "UPDATE_PAYMENT_RULES_SUCCESS",
    UPDATE_PAYMENT_RULES_FAILED: "UPDATE_PAYMENT_RULES_FAILED",
    UPDATE_PAYMENT_RULES_RESET: "UPDATE_PAYMENT_RULES_RESET",

    UPDATE_PAYMENT_RULES_STATUS: "UPDATE_PAYMENT_RULES_STATUS",
    UPDATE_PAYMENT_RULES_STATUS_SUCCESS: "UPDATE_PAYMENT_RULES_STATUS_SUCCESS",
    UPDATE_PAYMENT_RULES_STATUS_FAILED: "UPDATE_PAYMENT_RULES_STATUS_FAILED",
    UPDATE_PAYMENT_RULES_STATUS_RESET: "UPDATE_PAYMENT_RULES_STATUS_RESET",

    DELETE_PAYMENT_RULES: "DELETE_PAYMENT_RULES",
    DELETE_PAYMENT_RULES_SUCCESS: "DELETE_PAYMENT_RULES_SUCCESS",
    DELETE_PAYMENT_RULES_FAILED: "DELETE_PAYMENT_RULES_FAILED",
    DELETE_PAYMENT_RULES_RESET: "DELETE_PAYMENT_RULES_RESET",

    get_all_payemnt_rules: (query) => ({
        type: actions.GET_PAYMENT_RULES,
        query,
    }),

    get_payemnt_rules_details_by_id: (id) => ({
        type: actions.GET_PAYMENT_RULES_DETAILS_BY_ID,
        id,
    }),

    add_payemnt_rules: (data) => ({
        type: actions.ADD_PAYMENT_RULES,
        data,
    }),

    update_payemnt_rules: (id, data) => ({
        type: actions.UPDATE_PAYMENT_RULES,
        data,
        id,
    }),

    update_payemnt_rules_status: (data, id) => ({
        type: actions.UPDATE_PAYMENT_RULES_STATUS,
        data,
        id,
    }),

    delete_payemnt_rules: (id) => ({
        type: actions.DELETE_PAYMENT_RULES,
        id,
    }),
};

export default actions;
