const actions = {
    GET_TRANSACTIONS: "GET_TRANSACTIONS",
    GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
    GET_TRANSACTIONS_FAILED: "GET_TRANSACTIONS_FAILED",
    GET_TRANSACTIONS_RESET: "GET_TRANSACTIONS_RESET",

    CREATE_TRANSACTIONS: "CREATE_TRANSACTIONS",
    CREATE_TRANSACTIONS_SUCCESS: "CREATE_TRANSACTIONS_SUCCESS",
    CREATE_TRANSACTIONS_FAILED: "CREATE_TRANSACTIONS_FAILED",
    CREATE_TRANSACTIONS_RESET: "CREATE_TRANSACTIONS_RESET",

    UPDATE_TRANSACTIONS: "UPDATE_TRANSACTIONS",
    UPDATE_TRANSACTIONS_SUCCESS: "UPDATE_TRANSACTIONS_SUCCESS",
    UPDATE_TRANSACTIONS_FAILED: "UPDATE_TRANSACTIONS_FAILED",
    UPDATE_TRANSACTIONS_RESET: "UPDATE_TRANSACTIONS_RESET",

    get_transactions: (query) => ({
        type: actions.GET_TRANSACTIONS,
        query,
    }),

    create_transactions: (data) => ({
        type: actions.CREATE_TRANSACTIONS,
        data,
    }),

    update_transactions: (id, data) => ({
        type: actions.UPDATE_TRANSACTIONS,
        id,
        data,
    }),
};

export default actions;
