const actions = {
    GET_APPLICATION_CONFIG: "GET_APPLICATION_CONFIG",
    GET_APPLICATION_CONFIG_SUCCESS: "GET_APPLICATION_CONFIG_SUCCESS",
    GET_APPLICATION_CONFIG_FAILED: "GET_APPLICATION_CONFIG_FAILED",
    GET_APPLICATION_CONFIG_RESET: "GET_APPLICATION_CONFIG_RESET",

    UPDATE_APPLICATION_CONFIG: "UPDATE_APPLICATION_CONFIG",
    UPDATE_APPLICATION_CONFIG_SUCCESS: "UPDATE_APPLICATION_CONFIG_SUCCESS",
    UPDATE_APPLICATION_CONFIG_FAILED: "UPDATE_APPLICATION_CONFIG_FAILED",
    UPDATE_APPLICATION_CONFIG_RESET: "UPDATE_APPLICATION_CONFIG_RESET",

    get_application_config: () => ({
        type: actions.GET_APPLICATION_CONFIG,
    }),

    update_application_config: (data) => ({
        type: actions.UPDATE_APPLICATION_CONFIG,
        data,
    }),
};

export default actions;
