const actions = {
    GET_DELIVERY_OPTION: 'GET_DELIVERY_OPTION',
    GET_DELIVERY_OPTION_SUCCESS: 'GET_DELIVERY_OPTION_SUCCESS',
    GET_DELIVERY_OPTION_FAILED: 'GET_DELIVERY_OPTION_FAILED',

    GET_DELIVERY_OPTION_DETAILS: 'GET_DELIVERY_OPTION_DETAILS',
    GET_DELIVERY_OPTION_DETAILS_SUCCESS: 'GET_DELIVERY_OPTION_DETAILS_SUCCESS',
    GET_DELIVERY_OPTION_DETAILS_FAILED: 'GET_DELIVERY_OPTION_DETAILS_FAILED',

    ADD_DELIVERY_OPTION: 'ADD_DELIVERY_OPTION',
    ADD_DELIVERY_OPTION_SUCCESS: 'ADD_DELIVERY_OPTION_SUCCESS',
    ADD_DELIVERY_OPTION_FAILED: 'ADD_DELIVERY_OPTION_FAILED',

    UPDATE_DELIVERY_OPTION: 'UPDATE_DELIVERY_OPTION',
    UPDATE_DELIVERY_OPTION_SUCCESS: 'UPDATE_DELIVERY_OPTION_SUCCESS',
    UPDATE_DELIVERY_OPTION_FAILED: 'UPDATE_DELIVERY_OPTION_FAILED',

    DELETE_DELIVERY_OPTION: 'DELETE_DELIVERY_OPTION',
    DELETE_DELIVERY_OPTION_SUCCESS: 'DELETE_DELIVERY_OPTION_SUCCESS',
    DELETE_DELIVERY_OPTION_FAILED: 'DELETE_DELIVERY_OPTION_FAILED',

    get_all_delivery_option: (query) => ({
        type: actions.GET_DELIVERY_OPTION,
        query
    }),

    get_delivery_option_details: (id) => ({
        type: actions.GET_DELIVERY_OPTION_DETAILS,
        id
    }),

    add_delivery_option: (data) => ({
        type: actions.ADD_DELIVERY_OPTION,
        data,
    }),

    update_delivery_option: (data) => ({
        type: actions.UPDATE_DELIVERY_OPTION,
        data,
    }),

    delete_delivery_option: (id) => ({
        type: actions.DELETE_DELIVERY_OPTION,
        id,
    }),
};

export default actions;