const actions = {
    GET_BUSINESS_SERVICE_CHARGE: "GET_BUSINESS_SERVICE_CHARGE",
    GET_BUSINESS_SERVICE_CHARGE_SUCCESS: "GET_BUSINESS_SERVICE_CHARGE_SUCCESS",
    GET_BUSINESS_SERVICE_CHARGE_FAILED: "GET_BUSINESS_SERVICE_CHARGE_FAILED",

    GET_BUSINESS_SERVICE_CHARGE_DETAILS: "GET_BUSINESS_SERVICE_CHARGE_DETAILS",
    GET_BUSINESS_SERVICE_CHARGE_DETAILS_SUCCESS: "GET_BUSINESS_SERVICE_CHARGE_DETAILS_SUCCESS",
    GET_BUSINESS_SERVICE_CHARGE_DETAILS_FAILED: "GET_BUSINESS_SERVICE_CHARGE_DETAILS_FAILED",

    ADD_BUSINESS_SERVICE_CHARGE: "ADD_BUSINESS_SERVICE_CHARGE",
    ADD_BUSINESS_SERVICE_CHARGE_SUCCESS: "ADD_BUSINESS_SERVICE_CHARGE_SUCCESS",
    ADD_BUSINESS_SERVICE_CHARGE_FAILED: "ADD_BUSINESS_SERVICE_CHARGE_FAILED",
    ADD_BUSINESS_SERVICE_CHARGE_RESET: "ADD_BUSINESS_SERVICE_CHARGE_RESET",

    UPDATE_BUSINESS_SERVICE_CHARGE: "UPDATE_BUSINESS_SERVICE_CHARGE",
    UPDATE_BUSINESS_SERVICE_CHARGE_SUCCESS: "UPDATE_BUSINESS_SERVICE_CHARGE_SUCCESS",
    UPDATE_BUSINESS_SERVICE_CHARGE_FAILED: "UPDATE_BUSINESS_SERVICE_CHARGE_FAILED",
    UPDATE_BUSINESS_SERVICE_CHARGE_RESET: "UPDATE_BUSINESS_SERVICE_CHARGE_RESET",

    UPDATE_BUSINESS_SERVICE_CHARGE_STATUS: "UPDATE_BUSINESS_SERVICE_CHARGE_STATUS",
    UPDATE_BUSINESS_SERVICE_CHARGE_STATUS_SUCCESS: "UPDATE_BUSINESS_SERVICE_CHARGE_STATUS_SUCCESS",
    UPDATE_BUSINESS_SERVICE_CHARGE_STATUS_FAILED: "UPDATE_BUSINESS_SERVICE_CHARGE_STATUS_FAILED",
    UPDATE_BUSINESS_SERVICE_CHARGE_STATUS_RESET: "UPDATE_BUSINESS_SERVICE_CHARGE_STATUS_RESET",

    get_all_business_charge: (query) => ({
        type: actions.GET_BUSINESS_SERVICE_CHARGE,
        query,
    }),

    get_business_charge_details: (id) => ({
        type: actions.GET_BUSINESS_SERVICE_CHARGE_DETAILS,
        id,
    }),

    add_business_charge: (data) => ({
        type: actions.ADD_BUSINESS_SERVICE_CHARGE,
        data,
    }),

    update_business_charge: (id, data) => ({
        type: actions.UPDATE_BUSINESS_SERVICE_CHARGE,
        id,
        data,
    }),

    update_business_charge_status: (id) => ({
        type: actions.UPDATE_BUSINESS_SERVICE_CHARGE_STATUS,
        id,
    }),
};

export default actions;
