const actions = {
    GET_USER_PROFILE_SETUP: "GET_USER_PROFILE_SETUP",
    GET_USER_PROFILE_SETUP_SUCCESS: "GET_USER_PROFILE_SETUP_SUCCESS",
    GET_USER_PROFILE_SETUP_FAILED: "GET_USER_PROFILE_SETUP_FAILED",

    LIST_USER_PROFILE_SETUP: "LIST_USER_PROFILE_SETUP",
    LIST_USER_PROFILE_SETUP_SUCCESS: "LIST_USER_PROFILE_SETUP_SUCCESS",
    LIST_USER_PROFILE_SETUP_FAILED: "LIST_USER_PROFILE_SETUP_FAILED",

    GET_USER_PROFILE_SETUP_BY_ID: "GET_USER_PROFILE_SETUP",
    GET_USER_PROFILE_SETUP_BY_ID_SUCCESS: "GET_USER_PROFILE_SETUP_SUCCESS",
    GET_USER_PROFILE_SETUP_BY_ID_FAILED: "GET_USER_PROFILE_SETUP_FAILED",

    ADD_USER_PROFILE_SETUP: "ADD_USER_PROFILE_SETUP",
    ADD_USER_PROFILE_SETUP_SUCCESS: "ADD_USER_PROFILE_SETUP_SUCCESS",
    ADD_USER_PROFILE_SETUP_FAILED: "ADD_USER_PROFILE_SETUP_FAILED",
    ADD_USER_PROFILE_SETUP_RESET: "ADD_USER_PROFILE_SETUP_RESET",

    UPDATE_USER_PROFILE_SETUP: "UPDATE_USER_PROFILE_SETUP",
    UPDATE_USER_PROFILE_SETUP_SUCCESS: "UPDATE_USER_PROFILE_SETUP_SUCCESS",
    UPDATE_USER_PROFILE_SETUP_FAILED: "UPDATE_USER_PROFILE_SETUP_FAILED",
    UPDATE_USER_PROFILE_SETUP_RESET: "UPDATE_USER_PROFILE_SETUP_RESET",

    LIST_USER_PROFILE_SETUP_FOR_SELECT: "LIST_USER_PROFILE_SETUP_FOR_SELECT",
    LIST_USER_PROFILE_SETUP_FOR_SELECT_SUCCESS: "LIST_USER_PROFILE_SETUP_FOR_SELECT_SUCCESS",
    LIST_USER_PROFILE_SETUP_FOR_SELECT_FAILED: "LIST_USER_PROFILE_SETUP_FOR_SELECT_FAILED",

    list_user_profile_setup: (query) => ({
        type: actions.LIST_USER_PROFILE_SETUP,
        query,
    }),

    get_user_profile_setup_by_id: (id) => ({
        type: actions.GET_USER_PROFILE_SETUP_BY_ID,
        id,
    }),

    add_user_profile_setup: (data) => ({
        type: actions.ADD_USER_PROFILE_SETUP,
        data,
    }),

    add_user_profile_setup_reset: () => ({
        type: actions.ADD_USER_PROFILE_SETUP_RESET,
    }),

    update_user_profile_setup: (data, id) => ({
        type: actions.UPDATE_USER_PROFILE_SETUP,
        data,
        id,
    }),

    update_user_profile_setup_reset: () => ({
        type: actions.UPDATE_USER_PROFILE_SETUP_RESET,
    }),

    list_user_profile_setup_for_select: (query) => ({
        type: actions.LIST_USER_PROFILE_SETUP_FOR_SELECT,
        query,
    }),
};

export default actions;
