const actions = {
    GET_LOCALIZATION_DETAILS: "GET_LOCALIZATION_DETAILS",
    GET_LOCALIZATION_DETAILS_SUCCESS: "GET_LOCALIZATION_DETAILS_SUCCESS",
    GET_LOCALIZATION_DETAILS_FAILED: "GET_LOCALIZATION_DETAILS_FAILED",

    ADD_TRANSLATION_VALUE: "ADD_TRANSLATION_VALUE",
    ADD_TRANSLATION_VALUE_SUCCESS: "ADD_TRANSLATION_VALUE_SUCCESS",
    ADD_TRANSLATION_VALUE_FAILED: "ADD_TRANSLATION_VALUE_FAILED",
    ADD_TRANSLATION_VALUE_RESET: "ADD_TRANSLATION_VALUE_RESET",

    GET_TRANSLATION_VALUE: "GET_TRANSLATION_VALUE",
    GET_TRANSLATION_VALUE_SUCCESS: "GET_TRANSLATION_VALUE_SUCCESS",
    GET_TRANSLATION_VALUE_FAILED: "GET_TRANSLATION_VALUE_FAILED",
    GET_TRANSLATION_VALUE_RESET: "GET_TRANSLATION_VALUE_RESET",

    UPDATE_TRANSLATION_VALUE: "UPDATE_TRANSLATION_VALUE",
    UPDATE_TRANSLATION_VALUE_SUCCESS: "UPDATE_TRANSLATION_VALUE_SUCCESS",
    UPDATE_TRANSLATION_VALUE_FAILED: "UPDATE_TRANSLATION_VALUE_FAILED",
    UPDATE_TRANSLATION_VALUE_RESET: "UPDATE_TRANSLATION_VALUE_RESET",

    DELETE_TRANSLATION_VALUE: "DELETE_TRANSLATION_VALUE",
    DELETE_TRANSLATION_VALUE_SUCCESS: "DELETE_TRANSLATION_VALUE_SUCCESS",
    DELETE_TRANSLATION_VALUE_FAILED: "DELETE_TRANSLATION_VALUE_FAILED",
    DELETE_TRANSLATION_VALUE_RESET: "DELETE_TRANSLATION_VALUE_RESET",

    UPDATE_TRANSLATION_VALUE_STATUS: "UPDATE_TRANSLATION_VALUE_STATUS",
    UPDATE_TRANSLATION_VALUE_STATUS_SUCCESS: "UPDATE_TRANSLATION_VALUE_STATUS_SUCCESS",
    UPDATE_TRANSLATION_VALUE_STATUS_FAILED: "UPDATE_TRANSLATION_VALUE_STATUS_FAILED",
    UPDATE_TRANSLATION_VALUE_STATUS_RESET: "UPDATE_TRANSLATION_VALUE_STATUS_RESET",

    get_localization_details: (id) => ({
        type: actions.GET_LOCALIZATION_DETAILS,
        id,
    }),

    add_translation_value: (data) => ({
        type: actions.ADD_TRANSLATION_VALUE,
        data,
    }),

    get_translation_value: (id) => ({
        type: actions.GET_TRANSLATION_VALUE,
        id,
    }),

    update_translation_value: (id, data) => ({
        type: actions.UPDATE_TRANSLATION_VALUE,
        data,
        id,
    }),

    delete_translation_value: (id) => ({
        type: actions.DELETE_TRANSLATION_VALUE,
        id,
    }),

    update_translation_value_status: (id, data) => ({
        type: actions.UPDATE_TRANSLATION_VALUE_STATUS,
        data,
        id,
    }),
};

export default actions;
