const actions = {
    GET_REFERENCE: "GET_REFERENCE",
    GET_REFERENCE_SUCCESS: "GET_REFERENCE_SUCCESS",
    GET_REFERENCE_FAILED: "GET_REFERENCE_FAILED",

    ADD_REFERENCE: "ADD_REFERENCE",
    ADD_REFERENCE_SUCCESS: "ADD_REFERENCE_SUCCESS",
    ADD_REFERENCE_FAILED: "ADD_REFERENCE_FAILED",
    ADD_REFERENCE_RESET: "ADD_REFERENCE_RESET",

    UPDATE_REFERENCE: "UPDATE_REFERENCE",
    UPDATE_REFERENCE_SUCCESS: "UPDATE_REFERENCE_SUCCESS",
    UPDATE_REFERENCE_FAILED: "UPDATE_REFERENCE_FAILED",
    UPDATE_REFERENCE_RESET: "UPDATE_REFERENCE_RESET",

    GET_REFERENCE_DATA: "GET_REFERENCE_DATA",
    GET_REFERENCE_DATA_SUCCESS: "GET_REFERENCE_DATA_SUCCESS",
    GET_REFERENCE_DATA_FAILED: "GET_REFERENCE_DATA_FAILED",

    ADD_REFERENCE_DATA: "ADD_REFERENCE_DATA",
    ADD_REFERENCE_DATA_SUCCESS: "ADD_REFERENCE_DATA_SUCCESS",
    ADD_REFERENCE_DATA_FAILED: "ADD_REFERENCE_DATA_FAILED",
    ADD_REFERENCE_DATA_RESET: "ADD_REFERENCE_DATA_RESET",

    UPDATE_REFERENCE_DATA: "UPDATE_REFERENCE_DATA",
    UPDATE_REFERENCE_DATA_SUCCESS: "UPDATE_REFERENCE_DATA_SUCCESS",
    UPDATE_REFERENCE_DATA_FAILED: "UPDATE_REFERENCE_DATA_FAILED",
    UPDATE_REFERENCE_DATA_RESET: "UPDATE_REFERENCE_DATA_RESET",

    DELETE_REFERENCE_DATA: "DELETE_REFERENCE_DATA",
    DELETE_REFERENCE_DATA_SUCCESS: "DELETE_REFERENCE_DATA_SUCCESS",
    DELETE_REFERENCE_DATA_FAILED: "DELETE_REFERENCE_DATA_FAILED",
    DELETE_REFERENCE_DATA_RESET: "DELETE_REFERENCE_DATA_RESET",

    get_all_reference: (query) => ({
        type: actions.GET_REFERENCE,
        query,
    }),

    add_reference: (data) => ({
        type: actions.ADD_REFERENCE,
        data,
    }),

    update_reference: (id, data) => ({
        type: actions.UPDATE_REFERENCE,
        data,
        id,
    }),

    get_reference_data: (id, query) => ({
        type: actions.GET_REFERENCE_DATA,
        id,
        query,
    }),

    add_reference_data: (data) => ({
        type: actions.ADD_REFERENCE_DATA,
        data,
    }),

    update_reference_data: (data) => ({
        type: actions.UPDATE_REFERENCE_DATA,
        data,
    }),

    delete_reference_data: (id) => ({
        type: actions.DELETE_REFERENCE_DATA,
        id,
    }),
};

export default actions;
