name: PRODUCTION - Chariot 🟢

on:
    workflow_dispatch: # Manual

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            REACT_APP_NAME: "Chariot Admin"
            REACT_APP_API_BASE_URL: https://adminapi.chariotremit.com/api
            REACT_APP_VERSION: v1.0.0
            REACT_APP_POWERED_BY_COMPANY_LABEL: www.isendremit.com
            REACT_APP_POWERED_BY_COMPANY_URL: https://isendremit.com

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Build app
              run: npm run build

            - name: Transfer files to Charoit Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.Charoit_LIVE_Host }}
                  username: ${{ secrets.Charoit_LIVE_User }}
                  password: ${{ secrets.Charoit_LIVE_Password }}
                  source: "dist/"
                  target: "/home/admin/chariot_AdminUI"

            - name: SSH into Charoit Server and run command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.Charoit_LIVE_Host }}
                  username: ${{ secrets.Charoit_LIVE_User }}
                  password: ${{ secrets.Charoit_LIVE_Password }}
                  port: ${{ secrets.Charoit_LIVE_Port }}
                  script: |
                      sudo mv /home/admin/chariot_AdminUI/dist /home/admin/deploy/adminui &&
                      sudo chown -R www-data:www-data /home/admin/deploy/adminui/ &&
                      sudo rm -rf /var/www/html/adminui
                      sudo mv /home/admin/deploy/adminui /var/www/html/ &&
                      sudo systemctl daemon-reload &&
                      sudo systemctl restart nginx
