name: CI - Continuous Integration

on:
    push:
        branches:
            - main
            - dev-isend
    pull_request:
        branches:
            - main
            - dev-isend

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            REACT_APP_NAME: "Remittance Platform - Admin Panel"
            REACT_APP_API_BASE_URL: https://dummy-api-url.com/api
            REACT_APP_VERSION: v2.3.0
            REACT_APP_COPYRIGHT_TEXT_SGP: "Copyright &copy; {{year}} iSend Pte Ltd. All Rights reserved"
            REACT_APP_COPYRIGHT_TEXT_AUS: "Copyright &copy; {{year}} TransCash International Pty Ltd. All Rights reserved."
            REACT_APP_COPYRIGHT_TEXT_USA: "Copyright &copy; {{year}} ISend Pte. Ltd. All Rights reserved."

        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Eslint
              run: npm run lint:check

            - name: Prettier
              run: npm run prettier:check

            - name: Build app
              run: npm run build
