name: PRODUCTION - iSend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_NAME: "iSend"
      REACT_APP_API_BASE_URL: https://{country}remitadminapi.isendremit.com/api
      REACT_APP_VERSION: v2.3.0
      REACT_APP_COPYRIGHT_TEXT_SGP: "Copyright &copy; {{year}} iSend Pte Ltd. All Rights reserved"
      REACT_APP_COPYRIGHT_TEXT_AUS: "Copyright &copy; {{year}} TransCash International Pty Ltd. All Rights reserved."
      REACT_APP_COPYRIGHT_TEXT_USA: "Copyright &copy; {{year}} ISend Pte. Ltd. All Rights reserved."

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run:
            npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master

        env:
          SOURCE_DIR: dist/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_LIVE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
